Add USPTO Schema
dspinellis/alexandria3k pull request #24
Opened 2023-09-18 21:53 UTC by AggelosMargkas

2023-09-19 11:07 UTC, dspinellis requested changes
Good work!  Please address the comments, adding a reply to each one regarding its handling. (A thumbs up for done is fine.)

2023-09-19 11:07 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +            4: "relation/parent-doc/document-id/doc-number",
See above.

2023-09-19 11:07 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +        self.column_contents = {
See above.

2023-09-19 11:07 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +            ),
Find a way to remove duplication between the schema definition of agents, applicants, assignees.  See how it's done in ORCID.

2023-09-19 11:07 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +         Perform different sampling functionalities by passing a lambda expression.
Remove unneeded space.

2023-09-19 11:17 UTC, AggelosMargkas commented
> A thumbs up for done is fine

Thank you, I am on it!

2023-09-19 18:18 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +        self.column_contents = {
Just for clarifications the list `column_names` will contain the values of the fixed dictionary , right? I mean not the column names as shown inside the tablemeta object.

2023-09-19 20:37 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +        self.column_contents = {
Exactly!  Try it out on the Python REPL.

2023-09-19 21:07 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +def date_getter(date, part_of_date):
I withdrew my changes date remains as yyyymmdd.

2023-09-19 21:07 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +        self.column_contents = {
Works nice.

2023-09-19 21:09 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +        if col == 0:  # id
Should the `column_contents` list handle the the values of the first columns as well? I uploaded it just for the rest. Let me know if this is alright.

2023-09-20 06:42 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +        if col == 0:  # id
No need for the first columns.  See the Crossref implementation.

2023-09-20 11:46 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +        if col == 0:  # id
Excluded the id column on detail tables since they don't have children. Is this okay?

2023-09-20 13:31 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +        if col == 0:  # id
Great, I updated it.

2023-09-20 13:32 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +         Perform different sampling functionalities by passing a lambda expression.
Fixed that!

2023-09-20 13:33 UTC, AggelosMargkas commented on docs/schema/uspto.dot
> +	us_patents -> usp_icpr_classifications [headlabel="1…N", taillabel="1…N"];
Yes, I changed it accordingly. Only to tables have a  1..N relationship with `us_patents` table, the rest  stays as 0..N

2023-09-20 20:59 UTC, merged

2023-09-20 20:59 UTC, dspinellis commented
Well done!