Add USPTO example
dspinellis/alexandria3k pull request #25
Opened 2023-09-28 00:47 UTC by AggelosMargkas

Add my first example of results of data that run through the whole USPTO data.

Add the sql query into the uspto examples file. This SQL query is designed to extract information about the applicant population by country and year, focusing on the top 5 countries in terms of patent counts for the year 2022.

Add the graph representing the evolution of the population and show it on the README.

2023-09-30 12:33 UTC, dspinellis requested changes
Nice! I like the clear SQL code. Please also add the Python script that generates the chart.

2023-09-30 13:08 UTC, AggelosMargkas commented
> Nice! I like the clear SQL code. Please also add the Python script that generates the chart.

Added that, should I add the csv data file as well?

2023-10-01 05:26 UTC, dspinellis commented
Great! The CSV data is a generated file. We add the chart (which is also generated) so that it can appear in the README file. I'll ensure that the example can run automatically as part of integration testing and get back to you, if needed.

2023-10-05 19:46 UTC, dspinellis requested changes
So nice to see this contribution! I suggested a few changes.

2023-10-05 19:46 UTC, dspinellis commented on docs/app-eg.rst
> +-  `Top 5 USPTO applicants population by country and year
Top five US Patent Office applications by …

2023-10-05 19:46 UTC, dspinellis commented on docs/cli-eg.rst
> +Count USPTO top 5 applicant countries from 2005 to 2022
Obtain top-five US Patent Office application countries

2023-10-05 19:46 UTC, dspinellis commented on docs/cli-eg.rst
> +
For the USPTO dataset sampling is performed through a 
provided tuple argument named **data**. The tuple's first value is
a designator string that will be either "path" or "container".
Thus, sampling can be done either on compressed files represented
through the weekly issued patents (path) or on the patents' full text
(container) located within the issued file.
The tuple's second value is a USPTO Zip file path or the patent's text, respectively.

2023-10-05 19:46 UTC, dspinellis commented on docs/cli-eg.rst
> +   is named **data**. So, the first value of the tuple will data[0].
I covered it above, please remove the note.

2023-10-05 19:46 UTC, dspinellis commented on docs/downloading.rst
> +patent application published weekly from 2003 to present. This data are published
These data

2023-10-05 19:46 UTC, dspinellis commented on docs/downloading.rst
> +from the US Patent and Trademark Office (USPTO) and hence the data source acronym inside *alexandria3k*.
inside → used in

2023-10-05 19:46 UTC, dspinellis commented on docs/downloading.rst
> +
Add:
```
The shell script *examples/uspto/fetch.sh* can be used to download all USPTO data.
```

2023-10-05 19:46 UTC, dspinellis commented on examples/uspto/README.md
> +The graph illustrates the calculated population of applicants who are listed in the records of the US Patent and Trademark Office, focusing specifically on the top five countries of the year 2022.
The chart illustrates the number of applicants listed in the records of the US Patent and Trademark Office,
tracking those from the top five countries of the year 2022.

2023-10-05 19:46 UTC, dspinellis commented on examples/uspto/README.md
> +![Applicants Population by Country and year for the Top 5 Countries of 2022](./top5applicantcountries.png)
![Number of Applicants by Country and Year for the Top-Five Countries of 2022](./top5applicantcountries.png)Top-Five

2023-10-05 19:46 UTC, dspinellis commented on examples/uspto/plot_applicants_data.py
> +plt.show()
Shouldn't the last line save the data into a file?
Can the file be SVG, rather than PNG?

2023-10-14 13:36 UTC, AggelosMargkas commented
> So nice to see this contribution! I suggested a few changes.

Hello👋 and apologies for my late reply. I updated the changes and I believe they are ready to be seen. I changed the image format accordingly. 

I have this error on the CI log for the installation of the rdbunit.

```
Run git clone --depth=1 https://github.com/dspinellis/rdbunit.git
Cloning into 'rdbunit'...
make: *** No rule to make target 'install'.  Stop.
Error: Process completed with exit code 2.
```

Any idea how to resolve this?

2023-10-14 14:28 UTC, merged