Process to disambiguate author affiliations using gpt-4
dspinellis/alexandria3k pull request #40
Opened 2024-01-23 03:07 UTC by dtgupta

This process adds a different dimension to author affiliation disambiguation. It uses NLP to extract affiliations from text. This process produces better results than the currently implemented matching strategy. It has a matching rate of 81.24% as compared to 36.73% of the currently implemented algorithm. It also performs much better to match authors to multiple affiliations. This process adds value to the project as it helps researchers with more accurate affiliation results.

2024-01-23 08:15 UTC, dspinellis requested changes
This is very interesting work; well done!  I added some comments as a first approximation to code that can be merged.  Please also add tests for each process. Thank you again for the PR.

2024-01-23 08:15 UTC, dspinellis commented on src/alexandria3k/processes/distinguish_affiliations.py
> +    select_cursor_2 = database.cursor()
Please use more descriptive names.

2024-01-23 08:15 UTC, dspinellis commented on src/alexandria3k/processes/distinguish_affiliations.py
> +    This function is used to find the best affiliation match based on levenshtein distance.
Do not start your comments with "This function…" Just write in imperative voice what the function does. (In all functions.)

2024-01-23 08:15 UTC, dspinellis commented on src/alexandria3k/processes/distinguish_affiliations.py
> +            model="gpt-4-1106-preview",
Please put the model in a constant at the top-level of the file.

2024-01-23 08:15 UTC, dspinellis commented on src/alexandria3k/processes/link_aa_llm.py
> +        WHERE ror_id != 20233
What is this number?  Please document it and use it as a constant.

2024-01-23 08:55 UTC, dtgupta commented on src/alexandria3k/processes/distinguish_affiliations.py
> +""""This process is used to distinguish the affiliations mentioned in the crossref dataset."""
Is there a specific approach to writing a license or can I copy the license comment from the other link_aa_base_ror.py file?

2024-01-23 08:58 UTC, dtgupta commented on src/alexandria3k/processes/distinguish_affiliations.py
> +    match it to the ROR database based on levenshtein distance.
The library used to calculate this distance has the spelling mentioned in the comment (without the 'c'). Should I still change it?

2024-01-23 16:37 UTC, dspinellis commented on src/alexandria3k/processes/distinguish_affiliations.py
> +""""This process is used to distinguish the affiliations mentioned in the crossref dataset."""
You shouldn't invent new licenses 😃 Nor is it a good practice to mix different ones. So just copy-paste the existing text, replacing your name and setting the year to 2024.

2024-01-23 16:38 UTC, dspinellis commented on src/alexandria3k/processes/distinguish_affiliations.py
> +    match it to the ROR database based on levenshtein distance.
The `c` was my mistake, sorry. The comment was for you to capitalize it here, because it's  proper name.

2026-03-17 10:33 UTC, dspinellis commented
Closing due to lack of response.

2026-03-17 10:33 UTC, closed without merging