Add first table of new USPTO plugin
dspinellis/alexandria3k pull request #9
Opened 2023-06-17 13:11 UTC by AggelosMargkas

Initialize new plugin support of US Patent Grant Bibliographic data. Add _tables_ global variable with the first table of the data schema.

- Add first table "us_patent" of the plugin.
- Add properties that that have 1 to 1 relationship, with respect to the [DTD](https://en.wikipedia.org/wiki/Document_type_definition) rules of the dataset.

2023-06-18 21:31 UTC, dspinellis commented
Nice progress!

* [ ] Please squash the two commits into a single clean one. 
* [ ] Identify yourself in the copyright message as the plugin's author.
* [ ] Ensure you've run black and pylint

Prioritize importing the main table over adding more.

2023-06-19 15:50 UTC, AggelosMargkas commented
- [x] Squashed commits into one.

2023-06-20 08:04 UTC, dspinellis requested changes
Nice! Please perform the requested changes and resubmit as a single rebased commit.

2023-06-20 08:04 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +            ColumnMeta("status", description="Fot used for publishing."),
Please clarify `Fot`.

2023-06-20 08:04 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +                description="Filename of an instance of it's respective DTD.",
its ("it's" is a contraction of "it is")

2023-06-20 08:04 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +            ColumnMeta("date_publiced"),
published

2023-06-20 08:04 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +                description="From figures I have excluded unseen figures-to-publish*.",
Please clarify and recast in passive voice.

2023-06-20 08:23 UTC, AggelosMargkas commented on src/alexandria3k/data_sources/uspto.py
> +# Copyright (C) 2022-2023  Aggelos Margkas
Change to solid '2023' or to '2023-2024'?

2023-06-20 09:55 UTC, dspinellis commented on src/alexandria3k/data_sources/uspto.py
> +# Copyright (C) 2022-2023  Aggelos Margkas
You write the year(s) when you have authored the code, so 2023.

2023-06-21 10:29 UTC, dspinellis commented
Well done!

2023-06-21 10:29 UTC, merged